// Autogenerated from Pigeon (v18.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "UnifonicSdkApiPush.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

/// # iOS UN (UserNotification) symbols
///
/// Dart/Flutter translation of the iOS permissions API. In a future release,
/// we may replace this API with a consistent API for all platforms that require
/// permissions to show notifications to the user.
/// UNAuthorizationStatus: Constants indicating whether the app is allowed to
/// schedule notifications.
///
/// See the [Apple documentation](https://developer.apple.com/documentation/usernotifications/unnotificationsettings/1648391-authorizationstatus) for more information
@implementation UNIUNAuthorizationStatusBox
- (instancetype)initWithValue:(UNIUNAuthorizationStatus)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

/// The type of notification the user will see
///
/// See the [Apple documentation](https://developer.apple.com/documentation/usernotifications/unalertstyle) for more information
@implementation UNIUNAlertStyleBox
- (instancetype)initWithValue:(UNIUNAlertStyle)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

/// The current configuration of a notification setting
///
/// See the [Apple documentation](https://developer.apple.com/documentation/usernotifications/unnotificationsetting) for more information
@implementation UNIUNNotificationSettingBox
- (instancetype)initWithValue:(UNIUNNotificationSetting)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

/// Conditions to show/reveal notification content to the user
///
/// See the [Apple documentation](https://developer.apple.com/documentation/usernotifications/unshowpreviewssetting) for more information
@implementation UNIUNShowPreviewsSettingBox
- (instancetype)initWithValue:(UNIUNShowPreviewsSetting)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface UNIRemoteMessage ()
+ (UNIRemoteMessage *)fromList:(NSArray *)list;
+ (nullable UNIRemoteMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface UNINotification ()
+ (UNINotification *)fromList:(NSArray *)list;
+ (nullable UNINotification *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface UNIUNNotificationSettings ()
+ (UNIUNNotificationSettings *)fromList:(NSArray *)list;
+ (nullable UNIUNNotificationSettings *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation UNIRemoteMessage
+ (instancetype)makeWithNotification:(nullable UNINotification *)notification
    data:(nullable NSDictionary<NSString *, id> *)data {
  UNIRemoteMessage* pigeonResult = [[UNIRemoteMessage alloc] init];
  pigeonResult.notification = notification;
  pigeonResult.data = data;
  return pigeonResult;
}
+ (UNIRemoteMessage *)fromList:(NSArray *)list {
  UNIRemoteMessage *pigeonResult = [[UNIRemoteMessage alloc] init];
  pigeonResult.notification = [UNINotification nullableFromList:(GetNullableObjectAtIndex(list, 0))];
  pigeonResult.data = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable UNIRemoteMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [UNIRemoteMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.notification ? [self.notification toList] : [NSNull null]),
    self.data ?: [NSNull null],
  ];
}
@end

@implementation UNINotification
+ (instancetype)makeWithTitle:(nullable NSString *)title
    body:(nullable NSString *)body {
  UNINotification* pigeonResult = [[UNINotification alloc] init];
  pigeonResult.title = title;
  pigeonResult.body = body;
  return pigeonResult;
}
+ (UNINotification *)fromList:(NSArray *)list {
  UNINotification *pigeonResult = [[UNINotification alloc] init];
  pigeonResult.title = GetNullableObjectAtIndex(list, 0);
  pigeonResult.body = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable UNINotification *)nullableFromList:(NSArray *)list {
  return (list) ? [UNINotification fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.title ?: [NSNull null],
    self.body ?: [NSNull null],
  ];
}
@end

@implementation UNIUNNotificationSettings
+ (instancetype)makeWithAuthorizationStatus:(nullable UNIUNAuthorizationStatusBox *)authorizationStatus
    soundSetting:(nullable UNIUNNotificationSettingBox *)soundSetting
    badgeSetting:(nullable UNIUNNotificationSettingBox *)badgeSetting
    alertSetting:(nullable UNIUNNotificationSettingBox *)alertSetting
    notificationCenterSetting:(nullable UNIUNNotificationSettingBox *)notificationCenterSetting
    lockScreenSetting:(nullable UNIUNNotificationSettingBox *)lockScreenSetting
    carPlaySetting:(nullable UNIUNNotificationSettingBox *)carPlaySetting
    alertStyle:(nullable UNIUNAlertStyleBox *)alertStyle
    showPreviewsSetting:(nullable UNIUNShowPreviewsSettingBox *)showPreviewsSetting
    criticalAlertSetting:(nullable UNIUNNotificationSettingBox *)criticalAlertSetting
    providesAppNotificationSettings:(nullable NSNumber *)providesAppNotificationSettings
    announcementSetting:(nullable UNIUNNotificationSettingBox *)announcementSetting {
  UNIUNNotificationSettings* pigeonResult = [[UNIUNNotificationSettings alloc] init];
  pigeonResult.authorizationStatus = authorizationStatus;
  pigeonResult.soundSetting = soundSetting;
  pigeonResult.badgeSetting = badgeSetting;
  pigeonResult.alertSetting = alertSetting;
  pigeonResult.notificationCenterSetting = notificationCenterSetting;
  pigeonResult.lockScreenSetting = lockScreenSetting;
  pigeonResult.carPlaySetting = carPlaySetting;
  pigeonResult.alertStyle = alertStyle;
  pigeonResult.showPreviewsSetting = showPreviewsSetting;
  pigeonResult.criticalAlertSetting = criticalAlertSetting;
  pigeonResult.providesAppNotificationSettings = providesAppNotificationSettings;
  pigeonResult.announcementSetting = announcementSetting;
  return pigeonResult;
}
+ (UNIUNNotificationSettings *)fromList:(NSArray *)list {
  UNIUNNotificationSettings *pigeonResult = [[UNIUNNotificationSettings alloc] init];
  NSNumber *authorizationStatusAsNumber = GetNullableObjectAtIndex(list, 0);
  UNIUNAuthorizationStatusBox *authorizationStatus = authorizationStatusAsNumber == nil ? nil : [[UNIUNAuthorizationStatusBox alloc] initWithValue:[authorizationStatusAsNumber integerValue]];
  pigeonResult.authorizationStatus = authorizationStatus;
  NSNumber *soundSettingAsNumber = GetNullableObjectAtIndex(list, 1);
  UNIUNNotificationSettingBox *soundSetting = soundSettingAsNumber == nil ? nil : [[UNIUNNotificationSettingBox alloc] initWithValue:[soundSettingAsNumber integerValue]];
  pigeonResult.soundSetting = soundSetting;
  NSNumber *badgeSettingAsNumber = GetNullableObjectAtIndex(list, 2);
  UNIUNNotificationSettingBox *badgeSetting = badgeSettingAsNumber == nil ? nil : [[UNIUNNotificationSettingBox alloc] initWithValue:[badgeSettingAsNumber integerValue]];
  pigeonResult.badgeSetting = badgeSetting;
  NSNumber *alertSettingAsNumber = GetNullableObjectAtIndex(list, 3);
  UNIUNNotificationSettingBox *alertSetting = alertSettingAsNumber == nil ? nil : [[UNIUNNotificationSettingBox alloc] initWithValue:[alertSettingAsNumber integerValue]];
  pigeonResult.alertSetting = alertSetting;
  NSNumber *notificationCenterSettingAsNumber = GetNullableObjectAtIndex(list, 4);
  UNIUNNotificationSettingBox *notificationCenterSetting = notificationCenterSettingAsNumber == nil ? nil : [[UNIUNNotificationSettingBox alloc] initWithValue:[notificationCenterSettingAsNumber integerValue]];
  pigeonResult.notificationCenterSetting = notificationCenterSetting;
  NSNumber *lockScreenSettingAsNumber = GetNullableObjectAtIndex(list, 5);
  UNIUNNotificationSettingBox *lockScreenSetting = lockScreenSettingAsNumber == nil ? nil : [[UNIUNNotificationSettingBox alloc] initWithValue:[lockScreenSettingAsNumber integerValue]];
  pigeonResult.lockScreenSetting = lockScreenSetting;
  NSNumber *carPlaySettingAsNumber = GetNullableObjectAtIndex(list, 6);
  UNIUNNotificationSettingBox *carPlaySetting = carPlaySettingAsNumber == nil ? nil : [[UNIUNNotificationSettingBox alloc] initWithValue:[carPlaySettingAsNumber integerValue]];
  pigeonResult.carPlaySetting = carPlaySetting;
  NSNumber *alertStyleAsNumber = GetNullableObjectAtIndex(list, 7);
  UNIUNAlertStyleBox *alertStyle = alertStyleAsNumber == nil ? nil : [[UNIUNAlertStyleBox alloc] initWithValue:[alertStyleAsNumber integerValue]];
  pigeonResult.alertStyle = alertStyle;
  NSNumber *showPreviewsSettingAsNumber = GetNullableObjectAtIndex(list, 8);
  UNIUNShowPreviewsSettingBox *showPreviewsSetting = showPreviewsSettingAsNumber == nil ? nil : [[UNIUNShowPreviewsSettingBox alloc] initWithValue:[showPreviewsSettingAsNumber integerValue]];
  pigeonResult.showPreviewsSetting = showPreviewsSetting;
  NSNumber *criticalAlertSettingAsNumber = GetNullableObjectAtIndex(list, 9);
  UNIUNNotificationSettingBox *criticalAlertSetting = criticalAlertSettingAsNumber == nil ? nil : [[UNIUNNotificationSettingBox alloc] initWithValue:[criticalAlertSettingAsNumber integerValue]];
  pigeonResult.criticalAlertSetting = criticalAlertSetting;
  pigeonResult.providesAppNotificationSettings = GetNullableObjectAtIndex(list, 10);
  NSNumber *announcementSettingAsNumber = GetNullableObjectAtIndex(list, 11);
  UNIUNNotificationSettingBox *announcementSetting = announcementSettingAsNumber == nil ? nil : [[UNIUNNotificationSettingBox alloc] initWithValue:[announcementSettingAsNumber integerValue]];
  pigeonResult.announcementSetting = announcementSetting;
  return pigeonResult;
}
+ (nullable UNIUNNotificationSettings *)nullableFromList:(NSArray *)list {
  return (list) ? [UNIUNNotificationSettings fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.authorizationStatus == nil ? [NSNull null] : [NSNumber numberWithInteger:self.authorizationStatus.value]),
    (self.soundSetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.soundSetting.value]),
    (self.badgeSetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.badgeSetting.value]),
    (self.alertSetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.alertSetting.value]),
    (self.notificationCenterSetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.notificationCenterSetting.value]),
    (self.lockScreenSetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.lockScreenSetting.value]),
    (self.carPlaySetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.carPlaySetting.value]),
    (self.alertStyle == nil ? [NSNull null] : [NSNumber numberWithInteger:self.alertStyle.value]),
    (self.showPreviewsSetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.showPreviewsSetting.value]),
    (self.criticalAlertSetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.criticalAlertSetting.value]),
    self.providesAppNotificationSettings ?: [NSNull null],
    (self.announcementSetting == nil ? [NSNull null] : [NSNumber numberWithInteger:self.announcementSetting.value]),
  ];
}
@end

@interface UNIPushHostApiCodecReader : FlutterStandardReader
@end
@implementation UNIPushHostApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [UNINotification fromList:[self readValue]];
    case 129: 
      return [UNIRemoteMessage fromList:[self readValue]];
    case 130: 
      return [UNIUNNotificationSettings fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface UNIPushHostApiCodecWriter : FlutterStandardWriter
@end
@implementation UNIPushHostApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[UNINotification class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[UNIRemoteMessage class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[UNIUNNotificationSettings class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface UNIPushHostApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation UNIPushHostApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[UNIPushHostApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[UNIPushHostApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *UNIPushHostApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    UNIPushHostApiCodecReaderWriter *readerWriter = [[UNIPushHostApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpUNIPushHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UNIPushHostApi> *api) {
  SetUpUNIPushHostApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpUNIPushHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<UNIPushHostApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  /// Returns null if it doesn't exist.
  /// See [PushFlutterApi.onNotificationTap] to understand why a RemoteMessage is not provided here.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushHostApi.getNotificationTapWhichLaunchedTerminatedApp", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:UNIPushHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getNotificationTapWhichLaunchedTerminatedAppWithError:)], @"UNIPushHostApi api (%@) doesn't respond to @selector(getNotificationTapWhichLaunchedTerminatedAppWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSDictionary<NSString *, id> *output = [api getNotificationTapWhichLaunchedTerminatedAppWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushHostApi.getToken", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:UNIPushHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getTokenWithCompletion:)], @"UNIPushHostApi api (%@) doesn't respond to @selector(getTokenWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getTokenWithCompletion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushHostApi.backgroundFlutterApplicationReady", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:UNIPushHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(backgroundFlutterApplicationReadyWithError:)], @"UNIPushHostApi api (%@) doesn't respond to @selector(backgroundFlutterApplicationReadyWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api backgroundFlutterApplicationReadyWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushHostApi.onListenToOnNewToken", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:UNIPushHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(onListenToOnNewTokenWithError:)], @"UNIPushHostApi api (%@) doesn't respond to @selector(onListenToOnNewTokenWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api onListenToOnNewTokenWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushHostApi.onCancelToOnNewToken", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:UNIPushHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(onCancelToOnNewTokenWithError:)], @"UNIPushHostApi api (%@) doesn't respond to @selector(onCancelToOnNewTokenWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api onCancelToOnNewTokenWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  /// Pass true for the option you want permission to use
  /// Returns true if permission was granted.
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushHostApi.requestPermission", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:UNIPushHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(requestPermissionBadge:sound:alert:carPlay:criticalAlert:provisional:providesAppNotificationSettings:announcement:completion:)], @"UNIPushHostApi api (%@) doesn't respond to @selector(requestPermissionBadge:sound:alert:carPlay:criticalAlert:provisional:providesAppNotificationSettings:announcement:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        BOOL arg_badge = [GetNullableObjectAtIndex(args, 0) boolValue];
        BOOL arg_sound = [GetNullableObjectAtIndex(args, 1) boolValue];
        BOOL arg_alert = [GetNullableObjectAtIndex(args, 2) boolValue];
        BOOL arg_carPlay = [GetNullableObjectAtIndex(args, 3) boolValue];
        BOOL arg_criticalAlert = [GetNullableObjectAtIndex(args, 4) boolValue];
        BOOL arg_provisional = [GetNullableObjectAtIndex(args, 5) boolValue];
        BOOL arg_providesAppNotificationSettings = [GetNullableObjectAtIndex(args, 6) boolValue];
        BOOL arg_announcement = [GetNullableObjectAtIndex(args, 7) boolValue];
        [api requestPermissionBadge:arg_badge sound:arg_sound alert:arg_alert carPlay:arg_carPlay criticalAlert:arg_criticalAlert provisional:arg_provisional providesAppNotificationSettings:arg_providesAppNotificationSettings announcement:arg_announcement completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushHostApi.getNotificationSettings", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:UNIPushHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getNotificationSettingsWithCompletion:)], @"UNIPushHostApi api (%@) doesn't respond to @selector(getNotificationSettingsWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api getNotificationSettingsWithCompletion:^(UNIUNNotificationSettings *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushHostApi.areNotificationsEnabled", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:UNIPushHostApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(areNotificationsEnabledWithCompletion:)], @"UNIPushHostApi api (%@) doesn't respond to @selector(areNotificationsEnabledWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api areNotificationsEnabledWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface UNIPushFlutterApiCodecReader : FlutterStandardReader
@end
@implementation UNIPushFlutterApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [UNINotification fromList:[self readValue]];
    case 129: 
      return [UNIRemoteMessage fromList:[self readValue]];
    case 130: 
      return [UNIUNNotificationSettings fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface UNIPushFlutterApiCodecWriter : FlutterStandardWriter
@end
@implementation UNIPushFlutterApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[UNINotification class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[UNIRemoteMessage class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[UNIUNNotificationSettings class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface UNIPushFlutterApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation UNIPushFlutterApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[UNIPushFlutterApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[UNIPushFlutterApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *UNIPushFlutterApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    UNIPushFlutterApiCodecReaderWriter *readerWriter = [[UNIPushFlutterApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface UNIPushFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation UNIPushFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)onMessageMessage:(UNIRemoteMessage *)arg_message completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushFlutterApi.onMessage", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:UNIPushFlutterApiGetCodec()];
  [channel sendMessage:@[arg_message ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onBackgroundMessageMessage:(UNIRemoteMessage *)arg_message completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushFlutterApi.onBackgroundMessage", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:UNIPushFlutterApiGetCodec()];
  [channel sendMessage:@[arg_message ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onNotificationTapData:(NSDictionary<NSString *, id> *)arg_data completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushFlutterApi.onNotificationTap", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:UNIPushFlutterApiGetCodec()];
  [channel sendMessage:@[arg_data ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onNewTokenToken:(NSString *)arg_token completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushFlutterApi.onNewToken", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:UNIPushFlutterApiGetCodec()];
  [channel sendMessage:@[arg_token ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)onOpenNotificationSettingsWithCompletion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.unifonic_sdk_flutter_platform_interface.PushFlutterApi.onOpenNotificationSettings", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:UNIPushFlutterApiGetCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

