name: unifonic_sdk_flutter
description: Unifonic Flutter SDK for iOS and Android
version: 0.0.13
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  unifonic_sdk_flutter_platform_interface:
    git:
      url: https://github.com/UnifonicGit/unifonic-sdk-flutter.git
      path: unifonic_sdk_flutter_platform_interface
      ref: release/0.0.8
  unifonic_sdk_flutter_android:
    git:
      url: https://github.com/UnifonicGit/unifonic-sdk-flutter.git
      path: unifonic_sdk_flutter_android
      ref: release/0.0.9
  unifonic_sdk_flutter_ios:
    git:
      url: https://github.com/UnifonicGit/unifonic-sdk-flutter.git
      path: unifonic_sdk_flutter_ios
      ref: release/0.0.9
  http: ^1.0.0
  device_info_plus: ^9.1.0
  geolocator: ^10.0.0
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  package_info_plus: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: false
  plugin:
    platforms:
      android:
        default_package: unifonic_sdk_flutter_android
      ios:
        default_package: unifonic_sdk_flutter_ios