name: unifonic_sdk_flutter_ios
description: Unifonic Flutter SDK for iOS
version: 0.0.8
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  unifonic_sdk_flutter_platform_interface:
    git:
      url: https://github.com/UnifonicGit/unifonic-sdk-flutter.git
      path: "unifonic_sdk_flutter_platform_interface"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    implements: unifonic_sdk_flutter
    platforms:
      ios:
        pluginClass: PushPlugin
