name: unifonic_sdk_flutter_android
description: Unifonic Flutter SDK for Android
version: 0.0.5
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  unifonic_sdk_flutter_platform_interface:
    path: "../unifonic_sdk_flutter_platform_interface"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    implements: unifonic_sdk_flutter
    platforms:
      android:
        package: com.unifonic.sdk
        pluginClass: PushPlugin
