name: unifonic_sdk_flutter_platform_interface
description: Unifonic Flutter SDK for iOS and Android
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^18.0.0
  flutter_lints: ^3.0.2
